'use client';

import React, { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import AdminLayout from '@components/layout/AdminLayout';
import Button from '@components/ui/Button';
import Input from '@components/ui/Input';
import api from '@services/api';
import { School, SchoolApplication } from '@app-types/index';
import { useStore } from '@store/auth';

export default function SchoolApprovalsPage() {
  const { user, isAuthenticated, isLoading } = useStore(); const router = useRouter();
  const [applications, setApplications] = useState<SchoolApplication[]>([]); const [schools, setSchools] = useState<School[]>([]); const [passwords, setPasswords] = useState<Record<string, string>>({}); const [message, setMessage] = useState(''); const [search, setSearch] = useState('');
  const load = () => Promise.all([api.get<SchoolApplication[]>('/school-applications'), api.get<{ data: School[] }>('/schools', { params: { limit: 100 } })]).then(([applicationsResponse, schoolsResponse]) => { setApplications(applicationsResponse.data); setSchools(schoolsResponse.data.data); }).catch(() => setMessage('Could not load school records.'));
  useEffect(() => { if (!isLoading && (!isAuthenticated || user?.role !== 'conect_admin')) router.replace('/platform-login'); }, [isLoading, isAuthenticated, user?.role, router]);
  useEffect(() => { if (user?.role === 'conect_admin') load(); }, [user?.role]);
  const approve = async (application: SchoolApplication) => { setMessage(''); try { const response = await api.post(`/school-applications/${application.id}/approve`, { password: passwords[application.id] }); setMessage(`${application.schoolName} approved. Send ${response.data.admin.email} their temporary password through a secure channel.`); load(); } catch (error: any) { setMessage(error.response?.data?.message || 'Could not approve this school.'); } };
  const pending = applications.filter((item) => item.status === 'pending'); const listed = schools.filter((school) => `${school.name} ${school.city} ${school.state}`.toLowerCase().includes(search.toLowerCase()));
  return <AdminLayout title="Schools"><div className="mx-auto max-w-6xl space-y-8">{message && <p className="rounded-md bg-primary-50 p-3 text-sm text-primary-900">{message}</p>}<section><div className="mb-4 flex items-center justify-between"><div><h2 className="text-xl font-bold">Approval queue</h2><p className="mt-1 text-sm text-secondary-600">Verify each school before creating its school-admin login.</p></div><span className="rounded-full bg-amber-100 px-3 py-1 text-sm font-medium text-amber-900">{pending.length} pending</span></div><div className="space-y-4">{pending.map((application) => <article key={application.id} className="rounded-lg border border-secondary-200 bg-white p-5"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="text-lg font-bold">{application.schoolName}</h3><p className="text-sm text-secondary-600">{application.city}, {application.state} · {application.contactFirstName} {application.contactLastName}</p><p className="mt-1 text-sm text-secondary-600">{application.contactEmail} · {application.contactPhone}</p></div></div>{application.description && <p className="mt-4 text-sm text-secondary-700">{application.description}</p>}<div className="mt-5 flex max-w-lg flex-col gap-3 sm:flex-row sm:items-end"><Input label="Temporary password" type="password" value={passwords[application.id] || ''} onChange={(event) => setPasswords((current) => ({ ...current, [application.id]: event.target.value }))} helperText="At least 8 characters." /><Button type="button" onClick={() => approve(application)}>Approve</Button></div></article>)}{pending.length === 0 && <p className="rounded-lg border border-secondary-200 bg-white p-5 text-secondary-600">There are no schools awaiting approval.</p>}</div></section><section><div className="mb-4 flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><h2 className="text-xl font-bold">Schools on the platform</h2><p className="mt-1 text-sm text-secondary-600">{schools.length} verified school records.</p></div><div className="w-full sm:w-72"><Input aria-label="Search listed schools" placeholder="Search schools" value={search} onChange={(event) => setSearch(event.target.value)} /></div></div><div className="overflow-hidden rounded-lg border border-secondary-200 bg-white"><div className="overflow-x-auto"><table><thead><tr><th>School</th><th>Location</th><th>Curriculum</th><th>Applications</th><th>Verification</th></tr></thead><tbody>{listed.map((school) => <tr key={school.id}><td className="font-medium">{school.name}</td><td>{school.city}, {school.state}</td><td className="uppercase">{school.curriculum}</td><td>{school.applicationCount || 0}</td><td className="capitalize">{school.verificationStatus.replace(/_/g, ' ')}</td></tr>)}{listed.length === 0 && <tr><td colSpan={5} className="py-10 text-center text-secondary-600">No schools match this search.</td></tr>}</tbody></table></div></div></section></div></AdminLayout>;
}
