'use client';

import React, { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import AdminLayout from '@components/layout/AdminLayout';
import Button from '@components/ui/Button';
import Input from '@components/ui/Input';
import Textarea from '@components/ui/Textarea';
import Select from '@components/ui/Select';
import api from '@services/api';
import { ApplicationFormField, School, SchoolBranch } from '@app-types/index';
import { useStore } from '@store/auth';

const list = (value?: string[]) => value?.join('\n') || '';
const lines = (value: string) => value.split('\n').map((item) => item.trim()).filter(Boolean);
const formFields = (value: string): ApplicationFormField[] => value.split('\n').map((item) => item.split('|').map((part) => part.trim())).filter(([label, type]) => label && ['text', 'textarea', 'email', 'tel', 'date', 'select', 'file'].includes(type)).map(([label, type, required, options], index) => ({ id: `field-${index + 1}`, label, type: type as ApplicationFormField['type'], required: required?.toLowerCase() === 'required', options: type === 'select' ? (options || '').split(',').map((option) => option.trim()).filter(Boolean) : undefined }));

export default function SchoolProfilePage() {
  const { user, isAuthenticated, isLoading: authLoading } = useStore(); const router = useRouter();
  const [school, setSchool] = useState<School | null>(null); const [saving, setSaving] = useState(false); const [notice, setNotice] = useState('');
  useEffect(() => { if (!authLoading && (!isAuthenticated || user?.role !== 'school_admin')) router.replace('/school-login'); }, [authLoading, isAuthenticated, user?.role, router]);
  useEffect(() => { if (user?.role === 'school_admin') api.get<School>('/schools/me').then((response) => setSchool(response.data)).catch(() => router.replace('/admin/dashboard')); }, [user?.role, router]);
  const update = (field: keyof School, value: string) => setSchool((current) => current ? { ...current, [field]: value } : current);
  const addBranch = () => setSchool((current) => current ? { ...current, branches: [...(current.branches || []), { id: crypto.randomUUID(), name: '', address: '', city: '', state: '', capacity: undefined, applicationDeadline: undefined }] } : current);
  const updateBranch = (id: string, field: keyof SchoolBranch, value: string) => setSchool((current) => current ? { ...current, branches: current.branches?.map((branch) => ({ ...branch, ...(branch.id === id ? { [field]: field === 'capacity' || field === 'applicationFee' ? (value ? Number(value) : undefined) : value } : {}) })) } : current);
  const removeBranch = (id: string) => setSchool((current) => current ? { ...current, branches: current.branches?.filter((branch) => branch.id !== id) } : current);
  const upload = async (event: React.ChangeEvent<HTMLInputElement>, kind: 'gallery' | 'document' | 'application-form' | 'logo' | 'cover') => { const file = event.target.files?.[0]; if (!file || !school) return; setNotice('Uploading file...'); try { const form = new FormData(); form.append('file', file); form.append('kind', kind); const response = await api.post<School>(`/schools/${school.id}/uploads`, form); setSchool(response.data); setNotice(kind === 'application-form' ? 'Application form uploaded.' : 'File uploaded.'); } catch (error: any) { setNotice(error.response?.data?.message || 'Could not upload this file.'); } finally { event.target.value = ''; } };
  const save = async (event: React.FormEvent) => { event.preventDefault(); if (!school) return; setSaving(true); setNotice(''); try { const response = await api.patch<School>(`/schools/${school.id}`, school); setSchool(response.data); setNotice('Your public school profile has been saved.'); } catch (error: any) { setNotice(error.response?.data?.message || 'Could not save your changes.'); } finally { setSaving(false); } };
  if (!school) return <AdminLayout title="School Profile"><p>Loading your school profile…</p></AdminLayout>;
  return <AdminLayout title="School Profile"><form onSubmit={save} className="mx-auto max-w-4xl space-y-6">
    {notice && <p className="rounded-lg bg-primary-50 p-3 text-sm text-primary-800">{notice}</p>}
    <section className="rounded-xl bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Public profile</h2><div className="mt-5 grid gap-4 md:grid-cols-2"><Input label="School name" value={school.name} onChange={(e) => update('name', e.target.value)} required /><Input label="Public email" type="email" value={school.email} onChange={(e) => update('email', e.target.value)} required /><Input label="Phone" value={school.phone} onChange={(e) => update('phone', e.target.value)} required /><Input label="Website" type="url" value={school.website || ''} onChange={(e) => update('website', e.target.value)} helperText="The only external link shown on your public profile." /><Input label="Annual tuition fee (₦)" type="number" min="0" value={school.annualTuitionFee ?? ''} onChange={(e) => setSchool({ ...school, annualTuitionFee: e.target.value ? Number(e.target.value) : undefined })} helperText="Used for the parent budget filter." /><Input label="Admission form fee (₦)" type="number" min="30000" value={school.admissionFormFee ?? ''} onChange={(e) => setSchool({ ...school, admissionFormFee: e.target.value ? Number(e.target.value) : undefined })} helperText="Minimum ₦30,000. Parents pay this plus 10%; the school owes an additional 10% after a successful payment." /></div><Textarea className="mt-4" label="About your school" value={school.description || ''} onChange={(e) => update('description', e.target.value)} rows={5} /><Textarea className="mt-4" label="Address" value={school.address} onChange={(e) => update('address', e.target.value)} rows={2} /></section>
    <section className="rounded-xl bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Learning and admissions</h2><div className="mt-5 grid gap-4 md:grid-cols-3"><Select label="Curriculum" value={school.curriculum} onChange={(e) => update('curriculum', e.target.value)} options={['nigerian','igcse','ib','mixed'].map((value) => ({ value, label: value.toUpperCase() }))} /><Select label="Boarding" value={school.boardingOption} onChange={(e) => update('boardingOption', e.target.value)} options={['day','boarding','mixed'].map((value) => ({ value, label: value }))} /><Select label="Student gender" value={school.gender} onChange={(e) => update('gender', e.target.value)} options={['male','female','mixed'].map((value) => ({ value, label: value }))} /></div><Textarea className="mt-4" label="Programmes or classes" value={list(school.programmes)} onChange={(e) => setSchool({ ...school, programmes: lines(e.target.value) })} helperText="One programme or class per line." rows={4} /><Textarea className="mt-4" label="Admission requirements" value={list(school.admissionRequirements)} onChange={(e) => setSchool({ ...school, admissionRequirements: lines(e.target.value) })} helperText="One requirement per line. Parents see this on your school page." rows={5} /><Textarea className="mt-4" label="Application instructions" value={school.admissionInstructions || ''} onChange={(e) => update('admissionInstructions', e.target.value)} rows={4} /><Textarea className="mt-4" label="Online application form fields" value={(school.applicationFields || []).map((field) => `${field.label} | ${field.type} | ${field.required ? 'required' : 'optional'}${field.type === 'select' ? ` | ${(field.options || []).join(', ')}` : ''}`).join('\n')} onChange={(e) => setSchool({ ...school, applicationFields: formFields(e.target.value) })} helperText="One field per line: Label | type | required or optional. Types: text, textarea, email, tel, date, select, file. For select fields add options after a fourth |, separated by commas. File fields let parents upload required documents in the form." rows={8} /></section>
    <section className="rounded-xl bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Facilities, pictures, and documents</h2><p className="mt-2 text-sm text-secondary-600">Images and documents must be uploaded here; image URLs are not accepted.</p><Textarea className="mt-4" label="Facilities" value={list(school.facilities)} onChange={(e) => setSchool({ ...school, facilities: lines(e.target.value) })} helperText="One facility per line." rows={4} /><div className="mt-5 grid gap-4 md:grid-cols-2"><label className="block text-sm font-medium text-secondary-900">Upload logo<input className="mt-2 block w-full text-sm" type="file" accept="image/*" onChange={(e) => upload(e, 'logo')} /></label><label className="block text-sm font-medium text-secondary-900">Upload cover image<input className="mt-2 block w-full text-sm" type="file" accept="image/*" onChange={(e) => upload(e, 'cover')} /></label><label className="block text-sm font-medium text-secondary-900">Add gallery photo<input className="mt-2 block w-full text-sm" type="file" accept="image/*" onChange={(e) => upload(e, 'gallery')} /></label><label className="block text-sm font-medium text-secondary-900">Upload admission resource<input className="mt-2 block w-full text-sm" type="file" accept=".pdf,.doc,.docx,image/*" onChange={(e) => upload(e, 'document')} /></label></div>{school.admissionDocuments?.length ? <ul className="mt-3 list-disc space-y-1 pl-5 text-sm text-primary-700">{school.admissionDocuments.map((item) => <li key={item.url}><a href={item.url} target="_blank" rel="noreferrer">{item.name}</a></li>)}</ul> : null}</section>
    <section className="rounded-xl bg-white p-6 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">School branches</h2><p className="mt-1 text-sm text-secondary-600">Register each campus separately. Parents select their preferred branch when applying.</p></div><Button type="button" variant="outline" onClick={addBranch}>Add branch</Button></div><div className="mt-5 space-y-5">{school.branches?.map((branch, index) => <div key={branch.id} className="rounded-lg border border-secondary-200 p-4"><div className="mb-4 flex items-center justify-between"><h3 className="font-semibold">Branch {index + 1}</h3><button type="button" className="text-sm font-medium text-red-600" onClick={() => removeBranch(branch.id)}>Remove</button></div><div className="grid gap-4 md:grid-cols-2"><Input label="Branch name" value={branch.name} onChange={(e) => updateBranch(branch.id, 'name', e.target.value)} required /><Input label="Street address" value={branch.address} onChange={(e) => updateBranch(branch.id, 'address', e.target.value)} required /><Input label="City" value={branch.city} onChange={(e) => updateBranch(branch.id, 'city', e.target.value)} required /><Input label="State" value={branch.state} onChange={(e) => updateBranch(branch.id, 'state', e.target.value)} required /><Input label="Application capacity (optional)" type="number" min="1" value={branch.capacity ?? ''} onChange={(e) => updateBranch(branch.id, 'capacity', e.target.value)} /><Input label="Application deadline (optional)" type="date" value={branch.applicationDeadline || ''} onChange={(e) => updateBranch(branch.id, 'applicationDeadline', e.target.value)} /></div></div>)}{!school.branches?.length && <p className="rounded-lg bg-secondary-50 p-4 text-sm text-secondary-600">No branches registered. Add one only if your school has campuses parents must choose between.</p>}</div></section>
    <Button type="submit" isLoading={saving}>Save public profile</Button>
  </form></AdminLayout>;
}
